//! A recipe the engine generated by assessing what a thing is actually made of.
//!
//! `docs/PLAY.md` D15: **a composite thing is one node with a recipe, not a
//! pile of promoted nodes.** A wooden box is one node whose recipe describes
//! six walls; struck, it responds as one box; struck hard enough, one wall
//! comes away and becomes a node *at that moment*, and the recipe then
//! describes five walls plus the break.
//!
//! # Why this is not a seventh `Program`
//!
//! [`crate::morph::Program`] is a species table and D11 exists to stop it
//! growing. A box is not a kind of thing in the world — it is an arrangement of
//! parts, in exactly the sense D18 means when it says `Box` is a geometric
//! primitive and not a species: a cathedral and a crate are both boxes.
//!
//! So an assembly is not selected from a list of programs. It is *generated*,
//! by the engine, from what the parts and their joins actually are, and then
//! stored so the thing can be sampled again later. That is the third axiom
//! applied to structure rather than to chemistry: derive once, store the rule,
//! run the rule per individual. A tree grows under `Program::Tree`; cut it into
//! pieces, carve them and attach them and what comes back is not a tree and not
//! a new species either — it is a recipe the engine wrote down by looking.
//!
//! # A part is a body
//!
//! There is **one type for a thing inside a node**, and it is
//! [`crate::state::Body`]. An assembly's parts are bodies; the sampler's output
//! is bodies; a structural member is a body. Two types — one for things that
//! were sampled and one for things that were made — would be the engine knowing
//! how a thing came to be there, which is the same failure as "only a built
//! thing has a surface" one layer up, and it showed up immediately as a part
//! carrying an extent and an orientation that a body could not express.
//!
//! So a `Body` gained the three things a part knew and it did not: an
//! **orientation**, **half-extents** (`Vec3::ZERO` meaning "a sphere of
//! `radius`"), and the **substance** it is one of. What is left over is the
//! [`Join`], which is genuinely not a property of the thing — it is a
//! relationship between two of them, and it lives in a parallel list the way
//! `Topology`'s joints already do.
//!
//! D15 is explicit that weld, glue and grown-together are not three features:
//! they differ only in the join's substance and its area, and therefore in its
//! strength under D14's Griffith law. So a join stores exactly those two, and
//! the strength comes out of the same measurement everything else's does — see
//! [`Join::material`].
//!
//! # The two things it emits
//!
//! * a [`crate::morph::Skeleton`], so the existing structural solver decides
//!   which join fails without knowing an assembly from a tree;
//! * a set of [`crate::shape::Piece`]s, so the narrow phase strikes a *panel*
//!   with the panel's own material — which is D18's "material attaches per
//!   primitive", and the first thing in the engine that has needed it.
//!
//! # What it costs
//!
//! A `Body` is 244 bytes in memory against the 80 a purpose-built part was, and
//! that is the right trade only because **the wire format does not write a
//! body's worth per part.** A recipe entry persists a position, an orientation,
//! half-extents, a mass, a substance and a slot — everything else about a body
//! is regenerated from the node's matter when it is sampled, which is what
//! "derived, with shortcuts stored" means applied to a recipe. See
//! `persist::put_morphology`.

use crate::chem::SubstanceId;
use crate::math::{v3, Vec3};
use crate::morph::{Skeleton, NO_SUPPORT};
use crate::shape::Piece;
use crate::state::Body;

/// A part that is anchored rather than joined to another part.
pub const UNJOINED: u16 = u16::MAX;

/// What holds one part onto another.
///
/// Not a property of either part: a relationship between two of them, stored
/// in a list parallel to the parts the way `Topology`'s joints already are.
/// D15's whole claim about joining is here — weld, glue, mortar and
/// grown-together are one mechanism differing in **what the join is made of**
/// and **how much of it there is**, and both of those are measured rather than
/// named.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Join {
    /// Index of the part this one is held onto, or [`UNJOINED`] for a part
    /// that is simply there — the first part of an assembly, or one resting on
    /// the ground.
    pub to: u16,
    /// What the join is made of. `UNSPECIATED` means the join is the parts'
    /// own material: two pieces grown or fused into one, with no third
    /// substance between them.
    pub substance: SubstanceId,
    /// Cross-section of the join, m². What D14's strength is multiplied by to
    /// get the force it takes to part them.
    pub area: f64,
}

impl Join {
    /// A part held on by nothing.
    pub const NONE: Join =
        Join { to: UNJOINED, substance: SubstanceId::UNSPECIATED, area: 0.0 };

    /// Joined to `to` by `area` square metres of `substance`.
    pub fn new(to: u16, substance: SubstanceId, area: f64) -> Join {
        Join { to, substance, area: area.max(0.0) }
    }

    #[inline]
    pub fn is_joined(&self) -> bool {
        self.to != UNJOINED
    }

    /// The radius of a circle of the join's own area — the section the solver
    /// bends and shears, which is the seam and not the part.
    pub fn seam_radius(&self) -> f64 {
        if self.area > 0.0 {
            (self.area / std::f64::consts::PI).sqrt()
        } else {
            0.0
        }
    }

    /// **What the join is made of, derived and not tabulated.**
    ///
    /// The third axiom applied to the thing D15 says joins differ by. A
    /// substance's arrangement analyses to `Properties`, and `Material::of`
    /// turns those into a stiffness and a surface energy under the formation
    /// conditions the *node* is in — the same route a node's bulk material
    /// takes, and the same route a part's does. Nothing anywhere names glue,
    /// mortar or weld metal, and there is no table to add a row to.
    ///
    /// `None` when the join has no substance of its own, which means "as
    /// strong as the parts": two pieces grown or fused together have no third
    /// material between them, and the caller falls back to the part's own.
    pub fn material(
        &self,
        matter: &crate::state::Matter,
        reg: &crate::chem::Registry,
    ) -> Option<crate::material::Material> {
        let s = reg.get(self.substance)?;
        let formation = crate::material::Formation::of_matter(matter, &s.props);
        Some(crate::material::Material::of(&s.props, formation))
    }
}

/// A generated recipe: the parts of a composite and how they are joined.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Assembly {
    /// The parts themselves. Ordinary bodies: `Body::solid` states one.
    pub parts: Vec<Body>,
    /// What holds each part on, parallel to `parts`. Shorter than `parts` is
    /// read as [`Join::NONE`] for the rest, so a pile of unjoined pieces costs
    /// nothing to describe.
    pub joins: Vec<Join>,
}

impl Assembly {
    /// A recipe from parts and the joins that hold them, padded so the two
    /// lists are the same length.
    pub fn new(parts: Vec<Body>, joins: Vec<Join>) -> Assembly {
        let mut joins = joins;
        joins.resize(parts.len(), Join::NONE);
        Assembly { parts, joins }
    }

    /// A recipe from parts nothing holds together — a heap, or a single piece.
    pub fn loose(parts: Vec<Body>) -> Assembly {
        Assembly::new(parts, Vec::new())
    }

    /// What holds part `i` on.
    #[inline]
    pub fn join(&self, i: usize) -> Join {
        self.joins.get(i).copied().unwrap_or(Join::NONE)
    }

    pub fn is_empty(&self) -> bool {
        self.parts.is_empty()
    }

    pub fn len(&self) -> usize {
        self.parts.len()
    }

    /// Total mass of the parts, kg.
    pub fn mass(&self) -> f64 {
        self.parts.iter().map(|p| p.mass).sum()
    }

    /// The node radius these parts imply, metres.
    ///
    /// **Not the bounding radius**, and the difference cost a measurement to
    /// find. `matter.radius` means, everywhere in this engine, *the radius of
    /// the uniform sphere with the same mass distribution* — `summarise`
    /// reports it from the rms of what a node holds, and `sample` scales what
    /// it draws until it comes back. A uniform sphere has rms radius
    /// `sqrt(3/5) R`, so the factor is `1/sqrt(3/5)` = 1.291, and that constant
    /// appears identically in `sampler::radius_scale`.
    ///
    /// Stating the bounding radius here instead put a six-panel box's walls
    /// **1.87x too far out**: the recipe said the floor was 0.6 m down, the
    /// sampler read a target radius of 1.449 m (the corner diagonal), measured
    /// an rms of 0.6 from the part centres, and helpfully scaled the whole box
    /// up until the two agreed. A recipe that says where a wall is and a
    /// sampler that puts it somewhere else is the failure this whole phase is
    /// about.
    ///
    /// The rms is over the part *centres*, because that is what the sampler
    /// measures: the bodies it draws are one per part. A panel's own spread
    /// lives in its hull, which is where contact reads it — see
    /// [`Assembly::bound`] for the geometric answer.
    ///
    /// A recipe whose parts are all at the origin — one plank, on its own —
    /// has no rms to measure, and falls back to the widest part's own reach so
    /// that it has the size of a plank rather than a radius of zero. Anything
    /// with parts in more than one place uses the rms and *is not* clamped to
    /// the bound: clamping put the box back out by 1.095x, because a 1.2 m
    /// panel reaches further than the equivalent sphere of six of them and is
    /// supposed to.
    pub fn extent(&self) -> f64 {
        let m = self.mass();
        let widest = self.parts.iter().map(|p| p.reach()).fold(0.0f64, f64::max);
        if !(m > 0.0) {
            return widest;
        }
        let r2: f64 = self.parts.iter().map(|p| p.mass * p.pos.norm2()).sum::<f64>() / m;
        let r = 1.291 * r2.max(0.0).sqrt();
        if r > 0.0 {
            r
        } else {
            widest
        }
    }

    /// The true bounding radius about the composite's origin, metres — what
    /// actually has to be inside a sphere for the whole thing to be.
    ///
    /// Distinct from [`Assembly::extent`] on purpose; read that first.
    pub fn bound(&self) -> f64 {
        self.parts
            .iter()
            .map(|p| p.pos.norm() + p.reach())
            .fold(0.0f64, f64::max)
    }

    /// Centre of mass of the parts, in the composite's frame.
    pub fn centre_of_mass(&self) -> Vec3 {
        let m = self.mass();
        if !(m > 0.0) {
            return Vec3::ZERO;
        }
        let mut acc = Vec3::ZERO;
        for p in &self.parts {
            acc = acc + p.pos.scale(p.mass);
        }
        acc.scale(1.0 / m)
    }

    /// Byte cost of the recipe — the number D15's whole argument is about.
    /// In-memory byte cost of the recipe.
    ///
    /// **Not the number D15's argument is about**, which is the *persisted*
    /// size: a part is an ordinary `Body` here, carrying velocity, temperature
    /// and composition that the wire format does not write because they are
    /// regenerated from the node's matter. See `persist::assembly_bytes`.
    pub fn state_bytes(&self) -> usize {
        std::mem::size_of::<Assembly>()
            + self.parts.len() * std::mem::size_of::<Body>()
            + self.joins.len() * std::mem::size_of::<Join>()
    }

    /// Bytes this recipe persists as — what a part costs on the wire.
    pub fn wire_bytes(&self) -> usize {
        crate::persist::PART_WIRE_BYTES * self.parts.len() + 4
    }

    /// The next unused site name, so a part added later never reuses one.
    pub fn next_site(&self) -> u32 {
        self.parts.iter().map(|p| p.slot.wrapping_add(1)).max().unwrap_or(0)
    }

    /// Position of the part with this site name, if it is still here.
    ///
    /// A part's site name is its `Body::slot`, which is the same number the
    /// tree uses for the body it generates — so a site, a slot and a promoted
    /// child's index are one thing rather than three that have to agree.
    pub fn index_of_site(&self, site: u32) -> Option<usize> {
        self.parts.iter().position(|p| p.slot == site)
    }

    /// The structure the solver sees.
    ///
    /// One member per part, as a segment across the part's *longest* axis with
    /// a radius that preserves its cross-section. The structural solver reasons
    /// in beams — a member spans between joints and bends about its base — and
    /// a panel is a very stubby beam rather than a different kind of thing. The
    /// support forest is the join graph, so a part whose join fails takes
    /// everything joined through it, which is what `detach` already computes.
    ///
    /// Units are the composite's own metres, unlike a grown program's skeleton,
    /// and `sample_structured` is what reconciles the two.
    pub fn render(&self) -> Skeleton {
        let mut sk = Skeleton::with_capacity(self.parts.len());
        for (i, p) in self.parts.iter().enumerate() {
            let h = if p.is_boxed() {
                p.half
            } else {
                // A round part has no long axis; a segment through its centre
                // of its own radius is the honest beam for it.
                v3(p.radius, p.radius, p.radius)
            };
            // The longest axis is the span; the other two give the section.
            let (axis, span, a, b) = if h.x >= h.y && h.x >= h.z {
                (v3(1.0, 0.0, 0.0), h.x, h.y, h.z)
            } else if h.y >= h.z {
                (v3(0.0, 1.0, 0.0), h.y, h.x, h.z)
            } else {
                (v3(0.0, 0.0, 1.0), h.z, h.x, h.y)
            };
            // Equal-area radius, so a stubby panel carries the load its real
            // cross-section carries rather than the load a rod of its thinnest
            // dimension would.
            let radius = (4.0 * a * b / std::f64::consts::PI).sqrt().max(1e-9);
            // The part is turned, so the beam through it is too.
            let axis = p.orientation.rotate(axis);
            let join = self.join(i);
            let support = if join.is_joined() { join.to as u32 } else { NO_SUPPORT };
            sk.push_joined(
                p.pos - axis.scale(span),
                p.pos + axis.scale(span),
                p.mass,
                radius,
                support,
                p.slot,
                // A part with no join is anchored, and its base carries
                // whatever its own section carries.
                join.seam_radius(),
                join.substance,
            );
        }
        sk
    }

    /// What the assembly presents to a contact: one filled solid per part,
    /// each carrying its own material.
    ///
    /// D18's "material attaches per primitive", and the first thing in the
    /// engine that has needed it: a tree is one substance everywhere and a
    /// sampled rock is too, but a box of oak panels on a steel frame is not.
    /// `fallback` is what an unspeciated part is made of — the composite's own
    /// measured material — so a recipe nobody has described still presents
    /// something rather than nothing.
    pub fn pieces(
        &self,
        matter: &crate::state::Matter,
        reg: &crate::chem::Registry,
        fallback: crate::material::Material,
        fallback_substance: SubstanceId,
    ) -> Vec<Piece> {
        self.parts
            .iter()
            .map(|p| {
                let (material, substance) = match reg.get(p.substance) {
                    // Formation conditions are the *node's* — how hot it is and
                    // how fast it can shed that heat — applied to this part's
                    // own substance, which is exactly how `Material::measured`
                    // treats a mixture's pools. A part is not a separate object
                    // with a separate history; it is a piece of this node.
                    Some(s) => {
                        let f = crate::material::Formation::of_matter(matter, &s.props);
                        (crate::material::Material::of(&s.props, f), p.substance)
                    }
                    None => (fallback, fallback_substance),
                };
                Piece { hull: p.hull(), material, substance, mass: p.mass }
            })
            .collect()
    }

    /// Every part hanging off this one, itself included, by index.
    ///
    /// The join graph is a forest and this is the subtree under one part: break
    /// the join at the base of an arm and the whole arm comes away, which is
    /// what a load path failing actually does. Swept rather than walked,
    /// because parts are not stored parent-before-child and assuming they are
    /// is how half an arm gets left behind.
    pub fn joined_through(&self, site: u32) -> Vec<usize> {
        let Some(root) = self.index_of_site(site) else {
            return Vec::new();
        };
        let mut reached = vec![false; self.parts.len()];
        reached[root] = true;
        loop {
            let mut grew = false;
            for i in 0..self.parts.len() {
                if reached[i] {
                    continue;
                }
                let to = self.join(i).to;
                if to != UNJOINED && (to as usize) < reached.len() && reached[to as usize] {
                    reached[i] = true;
                    grew = true;
                }
            }
            if !grew {
                break;
            }
        }
        reached.iter().enumerate().filter(|(_, r)| **r).map(|(i, _)| i).collect()
    }

    /// Break the join holding one part on, and re-anchor whatever hung off it.
    ///
    /// **One part comes away, not an arm.** Breaking the join at the base of a
    /// branch removes that branch's *support*, and what the parts above it do
    /// next is a question for the solver on the frame after — they are
    /// unsupported, not airborne. Taking the whole subtree here would be the
    /// engine deciding that for them, and a box has no subtrees to take
    /// anyway: six panels joined to one is a star, and every break is one
    /// panel.
    ///
    /// **The part stays in the recipe.** A wall that comes off a box becomes a
    /// node of its own, which in this engine means a *promoted child*, and a
    /// promoted child's slot in its parent's body list is exactly how the tree
    /// says so — `children` runs parallel to `bodies` and `structural_mask`
    /// already partitions the promoted ones out of the structure. Storing a
    /// second answer on the part would be the second axiom failing by way of
    /// having two of them: whether a part is still attached is a join, and
    /// whether it is its own object is the tree, and the two are asked
    /// separately because they are different questions. Keeping the slot is
    /// also what lets the promoted child survive the edit at all — clearing the
    /// body list to regenerate a five-part recipe would orphan the very node
    /// the break just created.
    ///
    /// So a box that lost a wall is a six-part recipe with five joins and a
    /// break, which is what "the recipe now describes five walls plus the
    /// break" means once it is written down. Returns whether there was a join
    /// there to break.
    pub fn break_join(&mut self, site: u32) -> bool {
        let Some(root) = self.index_of_site(site) else {
            return false;
        };
        let was_joined = self.join(root).is_joined();
        self.joins.resize(self.parts.len(), Join::NONE);
        self.joins[root] = Join::NONE;
        // Anything that reached the ground through this part no longer does.
        for i in 0..self.joins.len() {
            if i != root && self.joins[i].to == root as u16 {
                self.joins[i] = Join::NONE;
            }
        }
        was_joined
    }

    /// A recipe for the parts that came away, about their own centre of mass.
    ///
    /// What the promoted child gets: the same parts, re-expressed in its frame,
    /// with joins that pointed outside the group cut. A wall that comes off a
    /// box is still a wall — that is the whole of D15's claim that breaking and
    /// joining are one transform, and a piece that arrived as a body with no
    /// shape would be the claim failing.
    pub fn taken(&self, sites: &[u32]) -> Assembly {
        let mut index = vec![UNJOINED; self.parts.len()];
        let mut parts: Vec<Body> = Vec::new();
        let mut joins: Vec<Join> = Vec::new();
        for &site in sites {
            if let Some(i) = self.index_of_site(site) {
                index[i] = parts.len() as u16;
                parts.push(self.parts[i]);
                joins.push(self.join(i));
            }
        }
        for j in joins.iter_mut() {
            if !j.is_joined() {
                continue;
            }
            match index.get(j.to as usize).copied().unwrap_or(UNJOINED) {
                // Its support stayed behind, so it is anchored now: a panel
                // whose neighbour did not come with it is not joined to
                // something that is no longer here.
                UNJOINED => *j = Join::NONE,
                new => j.to = new,
            }
        }
        let mut out = Assembly::new(parts, joins);
        let com = out.centre_of_mass();
        out.recentre(com);
        out
    }

    /// Re-express the parts about a new origin, which is what detaching a piece
    /// and giving it a node of its own costs.
    pub fn recentre(&mut self, origin: Vec3) {
        for p in self.parts.iter_mut() {
            p.pos = p.pos - origin;
        }
    }
}
