//! A recipe the engine generated by assessing what a thing is actually made of.
//!
//! `docs/PLAY.md` D15: **a composite thing is one node with a recipe, not a
//! pile of promoted nodes.** A wooden box is one node whose recipe describes
//! six walls; struck, it responds as one box; struck hard enough, one wall
//! comes away and becomes a node *at that moment*, and the recipe then
//! describes five walls plus the break.
//!
//! # Why this is not a seventh `Program`
//!
//! [`crate::morph::Program`] is a species table and D11 exists to stop it
//! growing. A box is not a kind of thing in the world — it is an arrangement of
//! parts, in exactly the sense D18 means when it says `Box` is a geometric
//! primitive and not a species: a cathedral and a crate are both boxes.
//!
//! So an assembly is not selected from a list of programs. It is *generated*,
//! by the engine, from what the parts and their joins actually are, and then
//! stored so the thing can be sampled again later. That is the third axiom
//! applied to structure rather than to chemistry: derive once, store the rule,
//! run the rule per individual. A tree grows under `Program::Tree`; cut it into
//! pieces, carve them and attach them and what comes back is not a tree and not
//! a new species either — it is a recipe the engine wrote down by looking.
//!
//! # What a part is
//!
//! A [`Part`] is one solid convex primitive with its own material, which is
//! D18's vocabulary exactly, plus the one thing D18 does not carry: **what it
//! is joined to, and what the join is made of.** D15 is explicit that weld,
//! glue and grown-together are not three features — they differ only in the
//! join's substance, and therefore in its strength under D14's Griffith law.
//! So the join is a substance and an area, and the strength comes out of the
//! same measurement everything else's does.
//!
//! # The two things it emits
//!
//! * a [`crate::morph::Skeleton`], so the existing structural solver decides
//!   which join fails without knowing an assembly from a tree;
//! * a set of [`crate::shape::Piece`]s, so the narrow phase strikes a *panel*
//!   with the panel's own material — which is D18's "material attaches per
//!   primitive", and the first thing in the engine that has needed it.
//!
//! # What it deliberately does not carry
//!
//! **A part has no orientation of its own.** Its half-extents are along the
//! composite's own axes, which is exact for a box and for anything else built
//! square, and wrong for a part set at an angle. Adding a quaternion per part
//! is four more doubles on a structure whose whole argument is that it costs
//! hundreds of bytes, and nothing in Phase 2 needs one; `BACKLOG.md` carries
//! the measurement and the trigger.

use crate::chem::SubstanceId;
use crate::math::{v3, Vec3};
use crate::morph::{Skeleton, NO_SUPPORT};
use crate::shape::{Hull, Piece};

/// A part that is anchored rather than joined to another part.
pub const UNJOINED: u16 = u16::MAX;

/// Rounding on a part's edges, as a fraction of its smallest half-extent.
///
/// A filled solid has to be convex and a sharp box is, so this is not needed
/// for correctness — it is needed because [`Hull::slab`] builds the box out of
/// corner spheres and a zero radius collapses all eight onto the corners,
/// leaving a point cloud whose support function is the same box but whose
/// contact normals near an edge are a corner's rather than a face's. A tenth of
/// the thinnest dimension is a plank's arris: small enough to leave the panel
/// flat where it is struck, large enough that an edge has a normal.
const EDGE_ROUNDING: f64 = 0.1;

/// One solid piece of an assembled thing.
///
/// Sizes and offsets are in **metres, in the composite's own frame** — not in
/// units of extent the way a grown program's skeleton is. A grown thing derives
/// its size from the mass it has accumulated; an assembled one is the size its
/// parts are, and its mass follows from them. The arrow between geometry and
/// mass points the other way, and storing metres is what says so.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Part {
    /// Centre of the part, in the composite's frame, metres.
    pub at: Vec3,
    /// Half-extents along the composite's axes, metres. A zero component is a
    /// sheet and is allowed.
    pub half: Vec3,
    /// Mass of this part, kg.
    pub mass: f64,
    /// What the part is made of. `UNSPECIATED` for a part nobody has described,
    /// which falls back to the composite's own mixture.
    pub substance: SubstanceId,
    /// The part this one is joined to, or [`UNJOINED`] for one that is simply
    /// there — the first part of an assembly, or a part resting on the ground.
    pub joined_to: u16,
    /// What the *join* is made of: weld, glue, mortar, grown-together. D15's
    /// "differing only in what the join is made of and therefore in its
    /// strength under D14". `UNSPECIATED` means the join is the parts'
    /// own material — two pieces grown or fused into one.
    pub join: SubstanceId,
    /// Cross-section of the join, m². What D14's strength is multiplied by to
    /// get the force it takes to part them.
    pub join_area: f64,
    /// Stable name for this part, so an event can refer to it and still mean
    /// the same part after the assembly has been regenerated.
    pub site: u32,
}

impl Part {
    /// A part with no join yet — what a piece is before it is attached.
    pub fn new(at: Vec3, half: Vec3, mass: f64, substance: SubstanceId, site: u32) -> Part {
        Part {
            at,
            half,
            mass: mass.max(0.0),
            substance,
            joined_to: UNJOINED,
            join: SubstanceId::UNSPECIATED,
            join_area: 0.0,
            site,
        }
    }

    /// Attach this part to another, with a join of a stated substance and area.
    pub fn joined(mut self, to: u16, join: SubstanceId, area: f64) -> Part {
        self.joined_to = to;
        self.join = join;
        self.join_area = area.max(0.0);
        self
    }

    /// Half the longest dimension, which is the part's own reach.
    pub fn reach(&self) -> f64 {
        let h = self.half;
        (h.x * h.x + h.y * h.y + h.z * h.z).sqrt()
    }

    /// The solid this part presents, in the composite's frame.
    pub fn hull(&self) -> Hull {
        let h = v3(self.half.x.abs(), self.half.y.abs(), self.half.z.abs());
        let thinnest = h.x.min(h.y).min(h.z);
        Hull::slab(self.at, h, thinnest * EDGE_ROUNDING)
    }

    /// Volume of the solid, m³. The rounding is ignored: it is a tenth of the
    /// thinnest dimension and subtracting it exactly would make a part's
    /// density depend on how its edges were finished.
    pub fn volume(&self) -> f64 {
        8.0 * self.half.x.abs() * self.half.y.abs() * self.half.z.abs()
    }
}

/// A generated recipe: the parts of a composite and how they are joined.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Assembly {
    pub parts: Vec<Part>,
}

impl Assembly {
    pub fn new(parts: Vec<Part>) -> Assembly {
        Assembly { parts }
    }

    pub fn is_empty(&self) -> bool {
        self.parts.is_empty()
    }

    pub fn len(&self) -> usize {
        self.parts.len()
    }

    /// Total mass of the parts, kg.
    pub fn mass(&self) -> f64 {
        self.parts.iter().map(|p| p.mass).sum()
    }

    /// The node radius these parts imply, metres.
    ///
    /// **Not the bounding radius**, and the difference cost a measurement to
    /// find. `matter.radius` means, everywhere in this engine, *the radius of
    /// the uniform sphere with the same mass distribution* — `summarise`
    /// reports it from the rms of what a node holds, and `sample` scales what
    /// it draws until it comes back. A uniform sphere has rms radius
    /// `sqrt(3/5) R`, so the factor is `1/sqrt(3/5)` = 1.291, and that constant
    /// appears identically in `sampler::radius_scale`.
    ///
    /// Stating the bounding radius here instead put a six-panel box's walls
    /// **1.87x too far out**: the recipe said the floor was 0.6 m down, the
    /// sampler read a target radius of 1.449 m (the corner diagonal), measured
    /// an rms of 0.6 from the part centres, and helpfully scaled the whole box
    /// up until the two agreed. A recipe that says where a wall is and a
    /// sampler that puts it somewhere else is the failure this whole phase is
    /// about.
    ///
    /// The rms is over the part *centres*, because that is what the sampler
    /// measures: the bodies it draws are one per part. A panel's own spread
    /// lives in its hull, which is where contact reads it — see
    /// [`Assembly::bound`] for the geometric answer.
    ///
    /// A recipe whose parts are all at the origin — one plank, on its own —
    /// has no rms to measure, and falls back to the widest part's own reach so
    /// that it has the size of a plank rather than a radius of zero. Anything
    /// with parts in more than one place uses the rms and *is not* clamped to
    /// the bound: clamping put the box back out by 1.095x, because a 1.2 m
    /// panel reaches further than the equivalent sphere of six of them and is
    /// supposed to.
    pub fn extent(&self) -> f64 {
        let m = self.mass();
        let widest = self.parts.iter().map(|p| p.reach()).fold(0.0f64, f64::max);
        if !(m > 0.0) {
            return widest;
        }
        let r2: f64 = self.parts.iter().map(|p| p.mass * p.at.norm2()).sum::<f64>() / m;
        let r = 1.291 * r2.max(0.0).sqrt();
        if r > 0.0 {
            r
        } else {
            widest
        }
    }

    /// The true bounding radius about the composite's origin, metres — what
    /// actually has to be inside a sphere for the whole thing to be.
    ///
    /// Distinct from [`Assembly::extent`] on purpose; read that first.
    pub fn bound(&self) -> f64 {
        self.parts
            .iter()
            .map(|p| p.at.norm() + p.reach())
            .fold(0.0f64, f64::max)
    }

    /// Centre of mass of the parts, in the composite's frame.
    pub fn centre_of_mass(&self) -> Vec3 {
        let m = self.mass();
        if !(m > 0.0) {
            return Vec3::ZERO;
        }
        let mut acc = Vec3::ZERO;
        for p in &self.parts {
            acc = acc + p.at.scale(p.mass);
        }
        acc.scale(1.0 / m)
    }

    /// Byte cost of the recipe — the number D15's whole argument is about.
    pub fn state_bytes(&self) -> usize {
        std::mem::size_of::<Assembly>() + self.parts.len() * std::mem::size_of::<Part>()
    }

    /// The next unused site name, so a part added later never reuses one.
    pub fn next_site(&self) -> u32 {
        self.parts.iter().map(|p| p.site.wrapping_add(1)).max().unwrap_or(0)
    }

    /// Position of the part with this site name, if it is still here.
    pub fn index_of_site(&self, site: u32) -> Option<usize> {
        self.parts.iter().position(|p| p.site == site)
    }

    /// The structure the solver sees.
    ///
    /// One member per part, as a segment across the part's *longest* axis with
    /// a radius that preserves its cross-section. The structural solver reasons
    /// in beams — a member spans between joints and bends about its base — and
    /// a panel is a very stubby beam rather than a different kind of thing. The
    /// support forest is the join graph, so a part whose join fails takes
    /// everything joined through it, which is what `detach` already computes.
    ///
    /// Units are the composite's own metres, unlike a grown program's skeleton,
    /// and `sample_structured` is what reconciles the two.
    pub fn render(&self) -> Skeleton {
        let mut sk = Skeleton::with_capacity(self.parts.len());
        for p in &self.parts {
            let h = v3(p.half.x.abs(), p.half.y.abs(), p.half.z.abs());
            // The longest axis is the span; the other two give the section.
            let (axis, span, a, b) = if h.x >= h.y && h.x >= h.z {
                (v3(1.0, 0.0, 0.0), h.x, h.y, h.z)
            } else if h.y >= h.z {
                (v3(0.0, 1.0, 0.0), h.y, h.x, h.z)
            } else {
                (v3(0.0, 0.0, 1.0), h.z, h.x, h.y)
            };
            // Equal-area radius, so a stubby panel carries the load its real
            // cross-section carries rather than the load a rod of its thinnest
            // dimension would.
            let radius = (4.0 * a * b / std::f64::consts::PI).sqrt().max(1e-9);
            let support = if p.joined_to == UNJOINED {
                NO_SUPPORT
            } else {
                p.joined_to as u32
            };
            // The seam, as the radius of a circle of the join's own area.
            // A part with no join is anchored and its base carries whatever its
            // own section carries.
            let seam = if p.join_area > 0.0 {
                (p.join_area / std::f64::consts::PI).sqrt()
            } else {
                0.0
            };
            sk.push_joined(
                p.at - axis.scale(span),
                p.at + axis.scale(span),
                p.mass,
                radius,
                support,
                p.site,
                seam,
            );
        }
        sk
    }

    /// What the assembly presents to a contact: one filled solid per part,
    /// each carrying its own material.
    ///
    /// D18's "material attaches per primitive", and the first thing in the
    /// engine that has needed it: a tree is one substance everywhere and a
    /// sampled rock is too, but a box of oak panels on a steel frame is not.
    /// `fallback` is what an unspeciated part is made of — the composite's own
    /// measured material — so a recipe nobody has described still presents
    /// something rather than nothing.
    pub fn pieces(
        &self,
        matter: &crate::state::Matter,
        reg: &crate::chem::Registry,
        fallback: crate::material::Material,
        fallback_substance: SubstanceId,
    ) -> Vec<Piece> {
        self.parts
            .iter()
            .map(|p| {
                let (material, substance) = match reg.get(p.substance) {
                    // Formation conditions are the *node's* — how hot it is and
                    // how fast it can shed that heat — applied to this part's
                    // own substance, which is exactly how `Material::measured`
                    // treats a mixture's pools. A part is not a separate object
                    // with a separate history; it is a piece of this node.
                    Some(s) => {
                        let f = crate::material::Formation::of_matter(matter, &s.props);
                        (crate::material::Material::of(&s.props, f), p.substance)
                    }
                    None => (fallback, fallback_substance),
                };
                Piece { hull: p.hull(), material, substance, mass: p.mass }
            })
            .collect()
    }

    /// Every part hanging off this one, itself included, by index.
    ///
    /// The join graph is a forest and this is the subtree under one part: break
    /// the join at the base of an arm and the whole arm comes away, which is
    /// what a load path failing actually does. Swept rather than walked,
    /// because parts are not stored parent-before-child and assuming they are
    /// is how half an arm gets left behind.
    pub fn joined_through(&self, site: u32) -> Vec<usize> {
        let Some(root) = self.index_of_site(site) else {
            return Vec::new();
        };
        let mut reached = vec![false; self.parts.len()];
        reached[root] = true;
        loop {
            let mut grew = false;
            for i in 0..self.parts.len() {
                if reached[i] {
                    continue;
                }
                let to = self.parts[i].joined_to;
                if to != UNJOINED && (to as usize) < reached.len() && reached[to as usize] {
                    reached[i] = true;
                    grew = true;
                }
            }
            if !grew {
                break;
            }
        }
        reached.iter().enumerate().filter(|(_, r)| **r).map(|(i, _)| i).collect()
    }

    /// Break the join holding one part on, and re-anchor whatever hung off it.
    ///
    /// **One part comes away, not an arm.** Breaking the join at the base of a
    /// branch removes that branch's *support*, and what the parts above it do
    /// next is a question for the solver on the frame after — they are
    /// unsupported, not airborne. Taking the whole subtree here would be the
    /// engine deciding that for them, and a box has no subtrees to take
    /// anyway: six panels joined to one is a star, and every break is one
    /// panel.
    ///
    /// **The part stays in the recipe.** A wall that comes off a box becomes a
    /// node of its own, which in this engine means a *promoted child*, and a
    /// promoted child's slot in its parent's body list is exactly how the tree
    /// says so — `children` runs parallel to `bodies` and `structural_mask`
    /// already partitions the promoted ones out of the structure. Storing a
    /// second answer on the part would be the second axiom failing by way of
    /// having two of them: whether a part is still attached is a join, and
    /// whether it is its own object is the tree, and the two are asked
    /// separately because they are different questions. Keeping the slot is
    /// also what lets the promoted child survive the edit at all — clearing the
    /// body list to regenerate a five-part recipe would orphan the very node
    /// the break just created.
    ///
    /// So a box that lost a wall is a six-part recipe with five joins and a
    /// break, which is what "the recipe now describes five walls plus the
    /// break" means once it is written down. Returns whether there was a join
    /// there to break.
    pub fn break_join(&mut self, site: u32) -> bool {
        let Some(root) = self.index_of_site(site) else {
            return false;
        };
        let was_joined = self.parts[root].joined_to != UNJOINED;
        {
            let p = &mut self.parts[root];
            p.joined_to = UNJOINED;
            p.join = SubstanceId::UNSPECIATED;
            p.join_area = 0.0;
        }
        // Anything that reached the ground through this part no longer does.
        for i in 0..self.parts.len() {
            if i != root && self.parts[i].joined_to == root as u16 {
                let p = &mut self.parts[i];
                p.joined_to = UNJOINED;
                p.join = SubstanceId::UNSPECIATED;
                p.join_area = 0.0;
            }
        }
        was_joined
    }

    /// A recipe for the parts that came away, about their own centre of mass.
    ///
    /// What the promoted child gets: the same parts, re-expressed in its frame,
    /// with joins that pointed outside the group cut. A wall that comes off a
    /// box is still a wall — that is the whole of D15's claim that breaking and
    /// joining are one transform, and a piece that arrived as a body with no
    /// shape would be the claim failing.
    pub fn taken(&self, sites: &[u32]) -> Assembly {
        let mut index = vec![UNJOINED; self.parts.len()];
        let mut parts: Vec<Part> = Vec::new();
        for &site in sites {
            if let Some(i) = self.index_of_site(site) {
                index[i] = parts.len() as u16;
                parts.push(self.parts[i]);
            }
        }
        for p in parts.iter_mut() {
            if p.joined_to == UNJOINED {
                continue;
            }
            let new = index.get(p.joined_to as usize).copied().unwrap_or(UNJOINED);
            if new == UNJOINED {
                p.joined_to = UNJOINED;
                p.join = SubstanceId::UNSPECIATED;
                p.join_area = 0.0;
            } else {
                p.joined_to = new;
            }
        }
        let mut out = Assembly::new(parts);
        let com = out.centre_of_mass();
        out.recentre(com);
        out
    }

    /// Re-express the parts about a new origin, which is what detaching a piece
    /// and giving it a node of its own costs.
    pub fn recentre(&mut self, origin: Vec3) {
        for p in self.parts.iter_mut() {
            p.at = p.at - origin;
        }
    }
}
